<div style="float: left; width: 70%">
    <?php
            $customer = $this->detail;
        ?>
        <div id="customer_detail">
            <?php foreach($customer as $value): ?>
            <h1>Customer: <?php echo $value['firstname'] . ' ' . $value['lastname']; ?></h1>
            <a href="<?php echo $this->baseUrl() ?>/customer/profile/update">Edit profile</a>
            <br>
            <?php
            //customize layout and style here
            echo $value['id'] . '<br>';
            echo $value['lastname'] . '<br>';
            echo $value['firstname'] . '<br>';
            endforeach;
            ?>

        </div>
        <div class="row">
            <?php
            if ($this->message) {

                if ($this->message['result'] == 'successful') {
                    echo '<p class="alert alert-success">' . $this->message['result'] . '</p>';
                } else {
                    echo '<p class="alert alert-warning">' . $this->message['result'] . '</p>';
                }
            }
            ?>
        </div>
    <?php  ?>
</div>

