<div class="inner register-inner">
    <?php
    switch ($this->message) {
        case Base_Constant_Client::SUCCESSFUL:
            echo '<p class="alert alert-success">Your password has been updated successfully.</p>';
            break;
        case '':
            break;
        default:
            echo '<p class="alert alert-danger">Sorry. ' . $this->message . '</p>';
            break;
    }
    ?>
    <div class="tab-content active" id="register-company-content">
        <form action="<?php echo $this->baseUrl(); ?>/<?php echo $this->moduleName; ?>/profile/changepassword"
              method="post" accept-charset="utf-8">
            <ul class="form-list">
                <li>
                    <div class="title">
                        <label>New Password</label>
                    </div>
                    <div class="input-wrapper">
                        <input type="password" name="password" class="input-text" required>
                        <span style="display: none" class="validate validate-error"></span>
                        <span class="required pseudo"></span>
                    </div>
                </li>
                <li>
                    <div class="title">
                        <label>ReEnter New Password</label>
                    </div>
                    <div class="input-wrapper">
                        <input type="password" name="repassword" class="input-text" required>
                        <span style="display: none" class="validate validate-error"></span>
                        <span class="required pseudo"></span>
                    </div>
                </li>
                <li>
                    <div class="button-set">
                        <button type="submit" value="1" name="update" class="button">
                            <span>Change Password</span></button>
                    </div>
                </li>
            </ul>
        </form>
    </div>
</div>
<div class="clear"></div>
</div>
</div>

<script type="text/javascript">
    <?php if(Zend_Registry::getInstance()->session->courier_profile->message != null){
       foreach(Zend_Registry::getInstance()->session->courier_profile->message as $key => $val){
            $element = '*[name="'.$key.'"]';
            $parent = 'parent()';
       ?>
    <?php if($key == "preferred_region"):
        $element = 'select[name="'.$key.'"]';
    endif;
    if($key == "preferred_delivery_suburb_ids"):
        $element = 'input.delivery_suburb';
        $parent = 'parent().parent().parent()';
    endif;
    if($key == "preferred_pickup_suburb_ids"):
        $element = 'input.pickup_suburb';
        $parent = 'parent().parent().parent()';
    endif; ?>
    $('<?php echo Zend_Registry::getInstance()->session->courier_profile->div; ?> <?php echo $element ?>').<?php echo $parent ?>.find('.validate-error').css('display', 'block');
    $('<?php echo Zend_Registry::getInstance()->session->courier_profile->div; ?> <?php echo $element ?>').<?php echo $parent ?>.find('.validate-error').html("<?php echo $this->escape($val); ?>");
    <?php }
     } ?>
</script>