<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title><?php echo $this->escape($this->siteName . ' | ' . $this->title); ?></title>
    <?php echo $this->headMeta(); ?>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php echo $this->optimizeHeadLink(); ?>
    <?php echo $this->optimizeHeadScript(); ?>

</head>
    <body class="user-body">
        <div class="container-fluid user-container">
            <div class="row user-vdict-space">&nbsp;</div>
            <div class="row">
                <div class="user-content-outter">
                    <div class="user-content">
                        <?php echo $this->layout()->content; ?>
                    </div>
                </div>
            </div>
            <div class="row user-vdict-space">&nbsp;</div>
        </div>
    </body>
</html>