<div style="width:100%;overflow: hidden">
    <ul class="left-menu hide-xs">
        <li><a href="<?php echo BASE_URL; ?>/<?php echo $this->moduleName; ?>/profile">Profile</a></li>
        <li><a href="<?php echo BASE_URL; ?>/pickup/index/book">Book a PickUp</a></li>
        <li><a href="<?php echo BASE_URL; ?>/<?php echo $this->moduleName; ?>">View Active Pickups</a></li>
        <li><a href="<?php echo BASE_URL; ?>/message">Message</a></li>
        <li><a href="<?php echo BASE_URL.UDS.$this->moduleName.UDS; ?>history">History</a></li>
    </ul>
</div>
