<?php
$auth = Zend_Auth::getInstance();
if ($auth->getStorage()->read() != null):
    $id = $auth->getStorage()->read()->id;
    $sort = $this->sort['sortField'];
    $type_sort_current = $this->sort['sortType'];
    $type_sort = $this->sort['type'];
    $icon_sort = 'sort_down.png';
    ?>
    <div class="big-wrapper">
        <div class="big-inner">
            <?php
            $msg_success = Zend_Registry::getInstance()->session->success->pickup;
            $msg_error = Zend_Registry::getInstance()->session->error->pickup;
            if ($msg_success) {
                ?>
                <span id="message"><p class="alert alert-success"><?php echo $msg_success['message']; ?></p></span>

                <?php
                Zend_Registry::getInstance()->session->success->pickup = '';
            }
            if ($msg_error) {
                ?>
                <span id="message"><p class="alert alert-danger"><?php echo $msg_error['message']; ?></p></span>

                <?php
                Zend_Registry::getInstance()->session->error->pickup = '';
            }
            ?>
            <span id="alert_changed" class="alert-danger"></span>
            <input type="hidden" value="1" id="check_status"/>
            <h1 class="title-inner"><?php echo Zend_Registry::getInstance()->controllerName=='pickup' ? 'Current pickups' : 'View History'?></h1>
            <?php echo $this->render('common/form_search.phtml'); ?>
            <div class="view-booking-table">
                <div class="table-wrapper">
                    <?php
                    if (count($this->pickups) > 0) {
                        ?>
                        <table cellpadding="0" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                       <?php
                        $dataHeadTitle = $this->dataHeadTitle;
                        foreach ($dataHeadTitle as $data) {
                            ?>
                            <th><?php
                                echo $this->escape($data['title']);
                                $sort_data['sortType'] = $sort == $data['sort_field'] ? $type_sort : 'ASC';
                                $sort_data['sortField'] = $data['sort_field'];
                                $data_Sort = $this->buildParams(1, $sort_data, $this->dataParams);
                                ?>
                                <a href="
                                <?php echo $this->buildUrl($data_Sort); ?>">
                                    <?php
                                    if ($sort) {
                                        if ($sort) {
                                            $icon_sort = $this->buildIcon($sort, $type_sort_current, $data['sort_field']);
                                        }
                                    }
                                    ?>
                                    <img
                                        src="<?php echo BASE_URL . UDS . 'static' . UDS . 'images' . UDS . $icon_sort; ?>"
                                        alt="<?php echo $icon_sort ?>">
                                </a>
                            </th>
                        <?php
                        }
                        ?>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                        $i = 1;
                        foreach ($this->pickups as $pickup) {
                            $pickup = new Base_Php_Overloader($pickup);
                            ?>
                            <tr id="item<?php echo $this->escape($pickup->id) ?>" onclick="PickupController.view(<?php echo $this->escape($pickup->id) ?>)">
                                <input type="hidden" name="pickup[]" value="<?php echo $this->escape($pickup->id) ?>"/>
                                <input type="hidden" name="status[]" value="<?php echo $this->escape($pickup->status) ?>"/>
                                <td><?php echo $this->escape($pickup->id) ?></td>
                                <td><?php echo $pickup->picked_up_active_time != '' ? date("d-M", strtotime($this->escape($pickup->picked_up_active_time))) : '' ?></td>
                                <td><?php echo $this->escape($pickup->from_address) ?></td>
                                <td><?php echo $this->escape($pickup->to_address) ?></td>
                                <td><?php echo $this->escape(Pickup_Constant_Server::$_STATUS[$pickup->status]) ?></td>
                                <td><?php echo
                                    $pickup->delivered_active_time != '' ? date("d-M", strtotime($this->escape($pickup->delivered_active_time))) : ''?></td>
                                <td><?php
                                    $target = $this->calculatorTarget($pickup,$this->dataConfig);
                                    echo $target['h']!==false && $target['m'] !==false ? $target['h'] . ' : ' . $target['m'] . ' Hours':'';
                                    ?>
                                </td>
                                <td><?php echo $this->escape($this->generateEscStatus($pickup,$target)) ?></td>
<!--                                <td>--><?php ////echo $this->escape($pickup->note) ?><!--</td>-->
                                <td><?php echo $this->escape($pickup->courier_search_name) ?></td>
                                <td><?php echo $this->escape($pickup->customer_search_name) ?></td>
                            </tr>
                        <?php
                        }
                        ?>
                        <input type="hidden" value="<?php echo $i - 1; ?><!--" id="total-list"/>
                    </tbody>
                </table>
                    <?php
                    }else{?>
                        <p class="no-result-search a-center a-center" >No results found</p>
                    <?php
                    }
                    ?>
            </div>
                <div class="paging">
                    <?php echo $this->paginationControl($this->pickups,
                        'Sliding',
                        'pagination.phtml', array('sort' => $this->sort,
                            'filter' => $this->dataParams)); ?>
                </div>
            </div>
            <?php echo $this->render('pickup/staff_view.phtml'); ?>
            <?php echo $this->render('pickup/rate_customer.phtml'); ?>
            <?php echo $this->render('pickup/rate_courier.phtml'); ?>
        </div>
    </div>
<?php endif; ?>
