<div style="text-align: center;">
    Welcome to Staff module - Manage Staff !
</div>
<div class="menu">
    <ul>
        <li>
            <a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->moduleName; ?>/user">Manage Staff</a>
        </li>
        <li>
            <a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->moduleName; ?>/customer">Manage Customer</a>
        </li>
        <li>
            <a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->moduleName; ?>/courier">Manage Courier</a>
        </li>
    </ul>
</div>
<!--            <ul>-->
<!--                <li>-->
<!--                    <a>-->
<!--                        <span></span>-->
<!--                    </a>-->
<!--                </li>-->
<!--            </ul>-->