
<div style="float: left; width: 70%">
    <?php
    $auth = Zend_Auth::getInstance();
    if($auth->getStorage()->read()!=null):
        $user = $auth->getStorage()->read()->detail;
    ?>
        <div id="customer_detail">
            <h1>Customer: <?php echo $user->firstname . ' ' . $user->lastname; ?></h1>
            <a href="<?php echo $this->baseUrl() ?>/courier/profile/update">Edit profile</a>
            <br>
            <?php
            //customize layout and style here
            echo $user->id . '<br>';
            echo $user->lastname . '<br>';
            echo $user->firstname . '<br>';
            ?>
        </div>
        <div class="row">
            <?php
            if ($this->message) {

                if ($this->message['result'] == 'successful') {
                    echo '<p class="alert alert-success">' . $this->message['result'] . '</p>';
                } else {
                    echo '<p class="alert alert-warning">' . $this->message['result'] . '</p>';
                }
            }
            ?>
        </div>
    <?php endif; ?>
</div>

