<div id="customer_detail">
    <form action="<?php echo $this->baseUrl(); ?>/courier/profile/add" method="post">
        <label for="company_name">Company Name</label>
        <input type="text" id="company_name" name="company_name" value="" />

        <label for="abn">Abn</label>
        <input type="text" id="abn" name="abn" value="" />

        <label for="contact_firstname">Contact Firstname</label>
        <input type="text" id="contact_firstname" name="contact_firstname" value="" />

        <label for="contact_lastname">contact lastname</label>
        <input type="text" id="contact_lastname" name="contact_lastname" value="" />

        <label for="email">email</label>
        <input type="text" id="email" name="email" value="" />

        <label for="alternative_email">alternative email</label>
        <input type="text" id="alternative_email" name="alternative_email" value="" />

        <label>general number</label>
        <input type="text" id="general_number" name="general_number" value="" />

        <label>contact_number</label>
        <input type="text" id="contact_number" name="contact_number" value="" />

        <label>address</label>
        <input type="text" id="address" name="address" value="" />

        <label>bank_bsb</label>
        <input type="text" id="bank_bsb" name="bank_bsb" value="" />

        <label>bank_account</label>
        <input type="text" id="bank_account" name="bank_account" value="" />

        <label>app_username</label>
        <input type="text" id="app_username" name="app_username" value="" />

        <label>mobile</label>
        <input type="text" id="mobile" name="mobile" value="" />

        <label>app_password</label>
        <input type="text" id="app_password" name="app_password" value="" />

        <label>bank_institution</label>
        <input type="text" id="bank_institution" name="bank_institution" value="" />

        <label for="customer_state">customer_state</label>
        <select id="customer_state" name="customer_state">
            <option value="0">--Please select--</option>
            <option selected="selected" value="" ></option>
        </select>

        <label for="postcode">postcode</label>
        <input type="text" id="postcode" name="postcode" value="" />

        <input type="submit" id="update" name="update" value="Register" />
    </form>
</div>