<!--<a type="button" class="btn btn-default" id="new" href="/--><?php //echo $this->moduleName; ?><!--/pickup/create">New Pickup</a>-->
<div id="search-pickup" class="searchbox">
    <table>
        <thead>
        <tr>
            <th><a type="button" class="btn btn-default" id="new" href="/--><?php //echo $this->moduleName; ?><!--/pickup/create">Search Destination suburb</a></th>
            <th><a type="button" class="btn btn-default" id="new" href="/--><?php //echo $this->moduleName; ?><!--/pickup/create">Search Booking Id</a></th>
            <th><a type="button" class="btn btn-default" id="new" href="/--><?php //echo $this->moduleName; ?><!--/pickup/create">Search courier</a></th>
        </tr>
        <tr>
            <th><a type="button" class="btn btn-default" id="new" href="/--><?php //echo $this->moduleName; ?><!--/pickup/create">Date from~~Date to</a></th>
            <th><a type="button" class="btn btn-default" id="new" href="/--><?php //echo $this->moduleName; ?><!--/pickup/create">Search Status</a></th>
            <th><a type="button" class="btn btn-default" id="new" href="/--><?php //echo $this->moduleName; ?><!--/pickup/create">Search customer</a></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th>

            </th>
        </tr>
        </tbody>
    </table>
</div>