<!--<a type="button" class="btn btn-default" href="/--><?php //echo $this->moduleName; ?><!--/index/add">Add</a>-->
<input type="submit" name="add" class="button" value="Add new">
<a type="button" class="btn btn-default" id="back_to_list" href="/<?php echo $this->moduleName; ?>/index/list">Back to list</a>
<!--<a type="button" class="btn btn-default" id="browse_images" target="_blank" href="/--><?php //echo $this->moduleName; ?><!--/image/browse">Browse images</a>-->