<div style="text-align: center;">
    Welcome to Pickup module !
</div>
<div class="menu">
    <ul>
        <li>
            <a href="/<?php echo $this->moduleName; ?>/pickup">Manage User</a>
        </li>
        <li>
            <a href="/<?php echo $this->moduleName; ?>/customer">Manage Customer</a>
        </li>
        <li>
            <a href="/<?php echo $this->moduleName; ?>/courier">Manage Courier</a>
        </li>
    </ul>
</div>