<h1>Pickup Page</h1>
<div>
    <form role="form" method="post" action="add">
        <h3>Book <span class="label label-default"> A Pickup</span></h3>
        <?php echo $button = $this->render('common/new_button' . $this->min . '.phtml'); ?>
        <div class="form-group">
            <label for="product_name">Pickup Address</label>
            <input type="text" class="form-control" placeholder="Pickup Address" id="from_address"
                   value="" name="from_address"/>
        </div>
        <div class="form-group">
            <label for="description">Delivery Address</label>
            <input type="text" class="form-control" placeholder="Delivery Address" id="to_address"
                   value="" name="to_address"/>
        </div>
        <div class="form-group">
            <label for="description">Base Price($)</label>
            <input type="text" class="form-control" id="base_charge_fee"
                   value="<?php echo $this->config[0]?>" name="base_charge_fee"/>
        </div>
        <div class="form-group">
            <label for="description">Request Signature on Delivery($)</label>
            <input type="text" class="form-control" id="delivery_signature_fee"
                   value="<?php echo $this->config[1]?>" name="delivery_signature_fee"/>
        </div>
        <div class="form-group">
            <label for="description">Insure Delivery($)</label>
            <input type="text" class="form-control" id="delivery_insure_fee"
                   value="<?php echo $this->config[2]?>" name="delivery_insure_fee"/>
        </div>
        <div class="form-group">
            <label for="description">Credit Card Charge(%)</label>
            <input type="text" class="form-control" id="credit_fee"
                   value="<?php echo $this->config[3]?>" name="credit_fee"/>
        </div>
        <?php echo $button; ?>
    </form>
</div>
<script type="text/plain" id="image-template">
    <img src="{url}" class="img-thumbnail img-responsive" />
</script>