<h1>Pickup Page</h1>
<div>
    <form role="form" method="post" action="">
        <h3>Book <span class="label label-default"> A Pickup</span></h3>

        <div class="form-group">
            <label for="from_address">Pickup Address</label>
            <input type="text" class="form-control" placeholder="Pickup Address" id="from_address"
                   value="" name="from_address"/>
        </div>
        <div class="form-group">
            <label for="to_address">Delivery Address</label>
            <input type="text" class="form-control" placeholder="Delivery Address" id="to_address"
                   value="" name="to_address"/>
        </div>
        <div class="form-group">
            <label for="detail">Pickup Detail</label>
            <input type="text" class="form-control" placeholder="Delivery Address" id="detail"
                   value="" name="detail"/>
        </div>
        <div class="form-group">
            <label for="base_charge_fee">Base Price($)</label>
            <input type="text" class="form-control" id="base_charge_fee"
                   value="<?php echo $this->config[0]?>" name="base_charge_fee"/>
        </div>
        <div class="form-group">
            <label for="delivery_signature_fee">Request Signature on Delivery($)</label>
            <input type="text" class="form-control" id="delivery_signature_fee"
                   value="<?php echo $this->config[1]?>" name="delivery_signature_fee"/>
        </div>
        <div class="form-group">
            <label for="delivery_insure_fee">Insure Delivery($)</label>
            <input type="text" class="form-control" id="delivery_insure_fee"
                   value="<?php echo $this->config[2]?>" name="delivery_insure_fee"/>
        </div>
        <div class="form-group">
            <label for="credit_fee">Credit Card Charge(%)</label>
            <input type="text" class="form-control" id="credit_fee"
                   value="<?php echo $this->config[3]?>" name="credit_fee"/>
        </div>
        <input type="submit" name="book" value="Book a pickup"/>
    </form>
</div>
<script type="text/plain" id="image-template">
    <img src="{url}" class="img-thumbnail img-responsive" />
</script>