<h1>Pickup detail</h1>
<?php
echo 'Status:' . $this->pickup->status . '<br>';
?>
<div>
    <form role="form" method="post" action="<?php echo $this->baseUrl()?>/pickup/index/changestatus">
        <input type="hidden" id="id" name="id" value="<?php echo $this->pickup->id?>">
        <h3>EDIT <span class="label label-default"> A Pickup</span></h3>
        <div class="form-group">
            <label for="product_name">Pickup Address</label>
            <input type="text" class="form-control" placeholder="Pickup Address" id="from_address"
                   value="<?php echo $this->pickup->from_address?>" name="from_address"/>
        </div>
        <div class="form-group">
            <label for="description">Delivery Address</label>
            <input type="text" class="form-control" placeholder="Delivery Address" id="to_address"
                   value="<?php echo $this->pickup->to_address?>" name="to_address"/>
        </div>
        <?php
        $current_sts = $this->pickup->status;
        $auth = Zend_Auth::getInstance();
        $auth_id = $auth->getStorage()->read()->id;
        $type= $auth->getStorage()->read()->auth_type;
        switch(true){
            case Pickup_Constant_Server::AWAITING==$current_sts:
                ?>
                <input type="hidden" id="status" value="<?php echo Pickup_Constant_Server::ASSIGNED?>">
                <input type="submit" name="status" value="<?php echo Pickup_Constant_Server::ASSIGNED?>">
                <?php
                break;
            case Pickup_Constant_Server::ASSIGNED == $current_sts:
                ?>
                <input type="submit" name="status" value="<?php echo Pickup_Constant_Server::PICKED_UP?>">
                <a type="button" class="btn btn-default" id="assign"
                   href="/<?php echo $this->moduleName; ?>/index/changestatus/id/<?php echo $this->pickup->id?>/status/<?php echo Pickup_Constant_Server::UNASSIGNED?>">
                    <?php echo Pickup_Constant_Server::UNASSIGNED?></a>
                <?php
                break;
            case Pickup_Constant_Server::CANCELLED==$current_sts:
                break;
            case Pickup_Constant_Server::PICKED_UP==$current_sts:
                ?>
                <input type="submit" name="status" value="<?php echo Pickup_Constant_Server::DELIVERED?>">
                <?php
                break;
            case Pickup_Constant_Server::DELIVERED==$current_sts:
                break;
            case Pickup_Constant_Server::ACCEPTED==$current_sts:
                break;
            case Pickup_Constant_Server::RATED==$current_sts:
                ?>
                <a type="button" class="btn btn-default" id="assign"
                   href="/<?php echo $this->moduleName; ?>/index/rate/id/<?php echo $this->pickup->id?>">
                    <?php echo Pickup_Constant_Server::RATED?></a>
                <?php
                break;
            default:
                break;
        }
        ?>
        <a type="button" class="btn btn-default" id="back_to_list" href="/<?php echo $this->moduleName; ?>/index/list">Back to list</a>
    </form>
</div>