<script>
    $('#detail_form').keydown(function(event){
        if(event.keyCode == 13) {
            event.preventDefault();
            return false;
        }
    });
</script>
<div class="form-list make-booking-inner" id="list_make">
    <?php if ($this->detail):
    $value = $this->detail;
    $current_sts = $value->status;
    if ($value['delivery_signature_fee'] > 0 && $current_sts == Pickup_Constant_Server::DELIVERED) {
        $new_status = Pickup_Constant_Server::ACCEPTED;
        $action = 'changeStatusPickup(' . $value['id'] . ')';
    } else {
        $new_status = Pickup_Constant_Server::RATED;
        $action = 'rateCourierPickup(' . $value['id'] . ')';
    }
    $req_tmp = $value['created'];
    $req_date = date("d M Y", strtotime($req_tmp));
    $req_time = date("g:i A", strtotime($req_tmp));
    $tmp = $value['delivered_active_time'];
    $time = $value['delivered_active_time'] ? strtotime($tmp) : (strtotime($value['created']) + $this->config[4] * 60 * 60);
    $due_date = date("d M Y", $time);
    $due_time = date("g:i A", $time);
    ?>
    <form method="post" id="detail_form">
        <div class="maps" id="map-canvas">
        </div>
        <div class="make-booking-inner">
            <ul class="form-list">
                <li>
                    <div class="title"><label>Pickup location<i class="question"></i></label>
                        <div class="label-content">
                            <label>Pickup location<i class="question"></i></label>
                            <p>Pickup location</p>
                        </div>
                    </div>
                    <div class="input-wrapper">
                        <?php
                        if($value['status']==Pickup_Constant_Server::AWAITING){
                        ?>
                        <input id="pickup_address" type="text" class="input-text" name="pickup_address" value="<?php echo $value['from_address'] ?>">
                        <?php
                        } else {
                            ?>
                            <input type="hidden" id="pickup_address" value="<?php echo $value['from_address']; ?>">
                            <?php echo nl2br($this->escape($value['from_address'])); ?>
                        <?php } ?>
                    </div>
                </li>
                <li>
                    <div class="title"><label>Note of Pickup location<i class="question"></i></label>
                        <div class="label-content">
                            <label>Note of Pickup location<i class="question"></i></label>
                            <p>Note of Pickup location</p>
                        </div>
                    </div>
                    <div class="input-wrapper">
                        <?php
                        if($value['status']==Pickup_Constant_Server::AWAITING){
                            ?>
                            <input id="note_pickup_address" type="text" class="input-text" name="note_pickup_address" value="<?php echo $value['note_from_address'] ?>">
                        <?php
                        } else {
                            ?>
                            <?php echo nl2br($this->escape($value['note_from_address'])); ?>
                        <?php } ?>
                    </div>
                </li>
                <li>
                    <div class="title"><label>Delivery Location<i class="question"></i></label>
                        <div class="label-content">
                            <label>Delivery Location<i class="question"></i></label>
                            <p>Delivery Location</p>
                        </div>
                    </div>
                    <div class="input-wrapper">
                        <?php
                        if($value['status']==Pickup_Constant_Server::AWAITING){
                            ?>
                            <input type="text" id="delivery_address" class="input-text" name="delivery_address" value="<?php echo $value['to_address'] ?>">
                        <?php
                        } else {
                            ?>
                            <input type="hidden" id="delivery_address" value="<?php echo $value['to_address']; ?>">
                            <?php echo nl2br($this->escape($value['to_address'])); ?>
                        <?php } ?>
                    </div>
                </li>
                <li>
                    <div class="title"><label>Note of Delivery location<i class="question"></i></label>
                        <div class="label-content">
                            <label>Note of Delivery location<i class="question"></i></label>
                            <p>Note of Delivery location</p>
                        </div>
                    </div>
                    <div class="input-wrapper">
                        <?php
                        if($value['status']==Pickup_Constant_Server::AWAITING){
                            ?>
                            <input id="note_delivery_address" type="text" class="input-text" name="note_delivery_address" value="<?php echo $value['note_to_address'] ?>">
                        <?php
                        } else {
                            ?>
                            <?php echo nl2br($this->escape($value['note_to_address'])); ?>
                        <?php } ?>
                    </div>
                </li>
                <li class="prefer">
                    <div class="big-inner pref-date">
                        <table class="top" width="100%" cellpadding="0" cellspacing="0">
                            <thead>
                            <tr>
                                <th colspan="3">Summary</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>REQUEST DATE:</td>
                                <td><?php echo $req_date; ?> </td>
                                <td>TIME: <?php echo $req_time; ?></td>
                            </tr>
                            <tr>
                                <td>DUE DATE:</td>
                                <td><?php echo $due_date ?> </td>
                                <td>TIME: <?php echo $due_time ?></td>
                            </tr>
                            </tbody>
                        </table>
                        <table class="bottom" width="100%" cellpadding="0" cellspacing="0">
                            <thead>
                            <tr>
                                <th colspan="3">Fees and charges</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>Base Pickup Fee</td>
                                <td>$<?php echo number_format((float)$value['base_charge_fee'], 2, '.', '') ?></td>
                                <td></td>
                            </tr>
                            <?php if ($value['delivery_insure_fee'] > 0) { ?>
                                <tr>
                                    <td>Insurance</td>
                                    <td> $<?php echo number_format((float)$value['delivery_insure_fee'], 2, '.', '') ?> </td>
                                    <td></td>
                                </tr>
                            <?php }
                            if ($value['delivery_signature_fee'] > 0) { ?>
                                <tr>
                                    <td>Signature on delivery</td>
                                    <td> $<?php echo number_format((float)$value['delivery_signature_fee'], 2, '.', '') ?></td>
                                    <td></td>
                                </tr>
                            <?php } ?>
                            <tr>
                                <td>Credit card fee</td>
                                <td>$<span id="credit_fee"><?php echo number_format((float)$value['credit_fee'], 2, '.', ''); ?></span></td>
                                <td></td>
                            </tr>
                            </tbody>
                            <tfoot>
                            <tr>
                                <td>TOTAL</td>
                                <td>$<span id="total_fee"><?php echo number_format((float)$value['total_fee'], 2, '.', '') ?></span></td>
                                <td></td>
                            </tr>
                            <?php
                            if(Pickup_Constant_Server::CANCELLED == $current_sts){ ?>
                                <tr>
                                    <td>CANCEL FEE</td>
                                    <td>$<span id="cancel_fee"><?php echo number_format((float)$value['cancel_fee'], 2, '.', '') ?></span></td>
                                    <td></td>
                                </tr>
                            <?php } ?>
                            </tfoot>
                        </table>
                        <div class="button-sets">
                            <?php
                            switch (true) {
                                case Pickup_Constant_Server::AWAITING == $current_sts:
                                    ?>
                                    <button onclick="PickupController.cancelPickup(<?php echo $value['id'] ?>);return false;" class="button book-button" name="cancel" value="cancel"><span>Cancel</span></button>
                                    <button onclick="PickupController.updatePickup(<?php echo $value['id'] ?>);return false;" class="button book-button" name="update" value="update"><span>Save</span></button>
                                    <?php
                                    break;
                                case Pickup_Constant_Server::ASSIGNED == $current_sts:
                                    ?>
                                    <button onclick="PickupController.cancelPickup(<?php echo $value['id'] ?>);return false;" class="button book-button" name="cancel" value="cancel"><span>Cancel</span></button>
                                    <?php
                                    break;
                                case Pickup_Constant_Server::CANCELLED == $current_sts:
                                    break;
                                case Pickup_Constant_Server::PICKED_UP == $current_sts:
                                    break;
                                case Pickup_Constant_Server::DELIVERED == $current_sts:
                                    ?>
                                    <input type="hidden" id="cur_status" value="<?php echo $current_sts ?>">
                                    <input type="hidden" id="new_status" value="<?php echo $new_status ?>">
                                    <button onclick="PickupController.<?php echo $action ?>;return false;" class="button book-button"><span><?php echo Pickup_Constant_Server::$_STATUS_ACTION[$new_status] ?></span></button>
                                    <?php
                                    if ($value['courier_rate_flag'] == 1) {?>
                                        <button onclick="PickupController.rateCustomerPickup(<?php echo $value['id'] ?>);return false;" class="button"><span>View Courier Ratings</span></button>
                                    <?php }
                                    break;
                                case Pickup_Constant_Server::ACCEPTED == $current_sts: ?>
                                    <button onclick="PickupController.rateCourierPickup(<?php echo $value['id'] ?>);return false;" class="button button-auto"><span>Add Rate</span></button>
                                    <?php
                                    if ($value['courier_rate_flag'] == 1) {?>
                                        <button onclick="PickupController.rateCustomerPickup(<?php echo $value['id'] ?>);return false;" class="button"><span>View Courier Ratings</span></button>
                                    <?php }
                                    break;
                                case Pickup_Constant_Server::RATED == $current_sts:
                                    ?>
                                    <button onclick="PickupController.rateCourierPickup(<?php echo $value['id'] ?>);return false;" class="button"><span>View Customer Ratings</span></button>
                                    <?php
                                    if ($value['courier_rate_flag'] == 1) { ?>
                                        <button onclick="PickupController.rateCustomerPickup(<?php echo $value['id'] ?>);return false;" class="button"><span>View Courier Ratings</span></button>
                                    <?php }
                                    break;
                                default:
                                    break;
                            } ?>
                            <button onclick="PickupController.cancel();return false;" class="button cancel-button"><span>Close</span></button>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </form>
    <?php endif; ?>
</div>
