<div class="big-inner">
    <h1 class="title-inner">View your bookings</h1>

    <div class="view-booking-table">
        <ul class="list-ms">
            <li class="head">
                <div class="title">
                    <span class="date">Date</span>
                    <span class="from">From</span>
                    <span class="to">To</span>
                    <span class="status">Status</span>
                    <span class="readed"></span>
                </div>
            </li>
            <li class="item active">
                <div class="title">
                    <span class="date">23-Nov</span>
                    <span class="from">rydalmere</span>
                    <span class="to">Mascot</span>
                    <span class="status">Assigned</span>
                    <span class="readed"></span>
                </div>
                <div class="content-item">
                    <div class="their">
                        <p>Hi it’s Mohammed. The traffic is really bad... running about <br/> 10 mins late. <br/>I’ll
                            buzz when I arrive?<br/> Sweet cuz??</p>
                    </div>
                    <div class="mine">
                        <p>Hi Mohammed. </p>
                    </div>
                    <div class="mine">
                        <p>No problem... remember you need to ring the door bell not the red button please?</p>
                    </div>
                    <div class="their">
                        <p>No worries...Here now.</br> This building is fully sick eh?</p>
                    </div>
                </div>
            </li>
            <li class="item">
                <div class="title">
                    <span class="date">23-Nov</span>
                    <span class="from">rydalmere</span>
                    <span class="to">Mascot</span>
                    <span class="status">Assigned</span>
                    <span class="readed"></span>
                </div>
                <div class="content-item">
                    <div class="their">
                        <p>Hi it’s Mohammed. The traffic is really bad... running about <br/> 10 mins late. <br/>I’ll
                            buzz when I arrive?<br/> Sweet cuz??</p>
                    </div>
                    <div class="mine">
                        <p>Hi Mohammed. </p>
                    </div>
                    <div class="mine">
                        <p>No problem... remember you need to ring the door bell not the red button please?</p>
                    </div>
                    <div class="their">
                        <p>No worries...Here now.</br> This building is fully sick eh?</p>
                    </div>
                </div>
            </li>
            <li class="item">
                <div class="title">
                    <span class="date">23-Nov</span>
                    <span class="from">rydalmere</span>
                    <span class="to">Mascot</span>
                    <span class="status">Assigned</span>
                    <span class="readed yes"></span>
                </div>
                <div class="content-item">
                    <div class="their">
                        <p>Hi it’s Mohammed. The traffic is really bad... running about <br/> 10 mins late. <br/>I’ll
                            buzz when I arrive?<br/> Sweet cuz??</p>
                    </div>
                    <div class="mine">
                        <p>Hi Mohammed. </p>
                    </div>
                    <div class="mine">
                        <p>No problem... remember you need to ring the door bell not the red button please?</p>
                    </div>
                    <div class="their">
                        <p>No worries...Here now.</br> This building is fully sick eh?</p>
                    </div>
                </div>
            </li>
        </ul>

        <div class="paging">
            <ul>
                <li><a href="#" title="" class="prev hide"></a></li>
                <li><a href="#" title="">1</a></li>
                <li><a href="#" title="">2</a></li>
                <li><a href="#" title="">3</a></li>
                <li><a href="#" title="" class="next"></a></li>
            </ul>
        </div>
    </div>
    <div class="make-booking-inner">

        <div class="big-inner pref-date">
            <table class="top" width="100%" cellpadding="0" cellspacing="0">
                <thead>
                <tr>
                    <th colspan="3">Summary</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>REQUEST DATE:</td>
                    <td>23 Nov 2014</td>
                    <td>TIME: 1:23PM</td>
                </tr>
                <tr>
                    <td>DUE DATE:</td>
                    <td>24 Nov 2014</td>
                    <td>TIME: 10:23AM</td>
                </tr>
                </tbody>
            </table>
            <table class="bottom" width="100%" cellpadding="0" cellspacing="0">
                <thead>
                <tr>
                    <th colspan="3">Fees and charges</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Base Pickup Fee:</td>
                    <td>$7.00</td>
                    <td><input class="checkbox-x" type="checkbox" checked="check"></td>
                </tr>
                <tr>
                    <td>Insurance</td>
                    <td>$3.50</td>
                    <td><input class="checkbox-x" type="checkbox" checked="check"></td>
                </tr>
                <tr>
                    <td>Signature on delivery</td>
                    <td>$2.00</td>
                    <td><input class="checkbox-x" type="checkbox" checked="check"></td>
                </tr>
                <tr>
                    <td>Same Day</td>
                    <td>$25.00</td>
                    <td><input class="checkbox-x" type="checkbox" name="" value=""></td>
                </tr>
                <tr>
                    <td>Express</td>
                    <td>$20.00</td>
                    <td><input class="checkbox-x" type="checkbox" name="" value=""></td>
                </tr>
                </tbody>
                <tfoot>
                <tr>
                    <td>TOTAL</td>
                    <td>$12:50</td>
                    <td></td>
                </tr>
                </tfoot>
            </table>
            <div class="button-sets">
                <button type="submit" class="button book-button"><span>SAVE</span></button>
                <button type="submit" class="button cancel-button"><span>CANCEL</span></button>
            </div>
        </div>

    </div>
</div>
<div class="clear"></div>

