<div class="big-inner">
	<div class="content-static">
		<h1>TERMS OF USE</h1>
		<p>Lorem ipsum dolor sit amet, alterum luptatum oporteat ne pro. Eos errem voluptatibus cu! Doctus regione suavitate eos at, mei abhorreant definitiones mediocritatem no. Ea dolores electram vix, an duo moderatius interesset, scripta malorum ei usu. Quo facilisis dignissim ex, ex nam nisl causae dissentiet, facer ridens veritus usu no. At sed porro nonumy suscipiantur, eos id dolorum conceptam. Sed ea sumo noluisse.</p>
		<h2>Heading 2</h2>
		<p>Eam labores facilisi no, in pro patrioque assueverit. Vim ne albucius deleniti. Ex nostro audiam fastidii ius? Has eu lorem affert inermis! Ea sed alii movet repudiandae, ex mel ullum commune? Justo dissentiunt ex mei, mei habeo nostro legimus eu! Eos aeterno persius fastidii cu, sed illud iudicabit id.</p>

		<h3>Heading 3</h3>
		<p>Eos et constituto adipiscing appellantur? Eu vix veri dicunt aeterno, ad pri dicta dolor senserit, pro oratio referrentur an? Invidunt praesent ut sea. Et dicta quando pericula duo! Novum invenire ei pro. Ea idque partem feugiat sea.</p>
		<ol>
			<li>Id nobis tritani discere per, eos ad inani fuisset. </li>
			<li>Et tibique copiosae menandri nec? </li>
			<li>Virtute electram usu at! Ea vis inani intellegam, ex mea alia omnis accumsan, ut tempor 
				vulputate vituperatoribus sit. Stet temporibus at duo, vero graeci invenire quo ex, oratio
				decore ad cum.</li>
			</ol>
			<p>
				Sit liber movet incorrupte in, autem audire malorum vel id, est no probo fugit vitae! Qui an quot intellegam! Vis ut inimicus rationibus elaboraret. Ridens nostrud splendide an vel, duo et sadipscing persequeris, in graeci voluptatibus mel. Te nisl accusata quaestio eam, sit veri iudico nominati ut.
			</p>
			<ul>
				<li>Ut quis eligendi sapientem vix, ei pro diceret oporteat insolens, iisque intellegebat qui ad? </li>
				<li>Vix congue praesent te? Qui an quod persecuti, reque eligendi definitiones no sit.</li>
				<li>Ex est nobis cotidieque! In graecis indoctum principes vis? Mel id populo utroque, nec ut putant
					prompta.</li>
				</ul>

				<p>Dicam albucius sapientem vis ex? Eum atqui everti dignissim in! Sale doming malorum sit an, feugiat democritum contentiones vel te. Augue praesent euripidis vix in. Choro dicant mnesarchum et sit, te aliquid omnesque contentiones ius! Per ad officiis forensibus. Te alia quaeque mei, an duo persius dissentiunt, et pri legere platonem?
				</p>
				<p>
					Nonumes facilis ius at, pri ipsum aliquid fabulas eu? Te cum impedit accumsan, vim id urbanitas vulputate eloquentiam. Decore exerci vituperatoribus cu pri, eu amet hinc eam? Cum quod tractatos suscipiantur ut, ius no erant homero adipiscing, pri alia laoreet ex! Audire copiosae reprehendunt ad his.
				</p>
				<p>
					Te velit nonumy legendos nec, veniam putent ceteros est ne. Possit perfecto eloquentiam an usu, eu 
				</p>
			</div>
		</div>
		<div class="clear"></div>