<div class="form-list make-booking-inner" id="list_make">
    <?php
    if ($this->region && $this->region != null) {
        $data = $this->region;
        ?>
        <div class="big-inner pref-date">
            <form action="<?php echo $this->baseUrl(); ?>/configuration/region/edit" method="post" id="form_update">
                <table class="bottom" width="100%" cellpadding="0" cellspacing="0">
                    <thead>
                    <tr>
                        <th colspan="3">Edit Region</th>
                    </tr>
                    </thead>
                    <tbody>
                    <input type="hidden" name="id" value="<?php echo $data['id'] ?>"/>
                    <tr>
                        <td>
                            <labe>Country</labe>
                        </td>
                        <td><select id="country">
                                <option value="<?php echo $data['country'] ?>"><?php echo $data['country'] ?></option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <labe>State</labe>
                        </td>
                        <td><input type="text" value="<?php echo $data['state'] ?>" id="state" maxlength="7"/></td>
                    </tr>
                    <tr>
                        <td>
                            <labe>Region</labe>
                        </td>
                        <td><input type="text" value="<?php echo $data['region'] ?>" id="region" maxlength="255"/></td>
                    </tr>
                    <tr>
                        <td>
                            <labe>Suburb</labe>
                        </td>
                        <td><input type="text" value="<?php echo $data['suburb'] ?>" id="suburb" maxlength="255"/></td>
                    </tr>
                    <tr>
                        <td>
                            <labe>Postcode</labe>
                        </td>
                        <td><input type="number" value="<?php echo $data['postcode'] ?>" id="postcode" maxlength="5"/></td>
                    </tr>
                    </tbody>
                </table>
                <div class="button-sets">
                    <button onclick="ConfigurationController.updateRegion(<?php echo $data['id'] ?>);return false;" class="button book-button" name="edit"><span>Save</span></button>
                    <button onclick="ConfigurationController.cancel();return false;" class="button cancel-button" name="cancel"><span>Cancel</span></button>
                </div>
            </form>
        </div>
    <?php
    }
    ?>
</div>